# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Install Maven 3.9.11 manually
- script: |
    curl -sL https://downloads.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz -o maven.tar.gz
    tar -xzf maven.tar.gz
    sudo mv apache-maven-3.9.11 /opt/maven
    echo "##vso[task.setvariable variable=PATH]/opt/maven/bin:$(PATH)"
    mvn -v
  displayName: "Install Maven 3.9.11"
  - task: Maven@3
  inputs:
  
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
